spring.application.name=job-scheduler-api

spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/myapp
spring.datasource.password=mysecretpassword

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=10
# This queue will be used if all workers are busy.
spring.task.execution.pool.queue-capacity=1000
